$ANSIBLE_VAULT;1.1;AES256
63666231366436356166333761323539353635316131343134356130373934643266366263343265
6563626134366263383933313766633064643333396233650a323337636533626536373765333830
33636233343638396363383230326232663466363765393731326266353137663663636630623230
3633383637636666330a306366636262353561653131366262366563373236306236386264646663
62643639393664653038666165373066643230363131626130333934656331316465363730633666
3532366133643636323231623937633930656161336132653764
